# Generated by Django 5.2.4 on 2025-07-23 15:29

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['-created_at'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='URL de imagen externa (fallback)', null=True),
        ),
    ]
